#Resources/config/routing.yml

oc_platform_home:
  path:    /{page}
  defaults: 
      _controller : OCPlatformBundle:Advert:index 
      page:    1
  requirements:
    page: \d*



oc_platform_view:
  path:    /advert/{id}
  defaults: { _controller : OCPlatformBundle:Advert:view }
  requirements:
    id:    \d+ #Doit être présent au moins une fois



oc_platform_add:
  path:    /add 
  defaults: 
      _controller : OCPlatformBundle:Advert:add 
  

oc_platform_edit:
  path:    /edit/{id}
  defaults:
    _controller: OCPlatformBundle:Advert:edit
  requirements:
    id:    \d+

oc_platform_delete:
  path:    /delete/{id}
  defaults:
    _controller: OCPlatformBundle:Advert:delete
  requirements:
    id:    \d+

oc_platform_view_slug:
  path:    /{year}/{slug}.{format}
  defaults: 
      _controller : OCPlatformBundle:Advert:viewSlug 
      format:    html #Le format par défaut est le HTML   
  requirements:
    year:    \d{4}
    format:    html|xml


oc_platform_list_adverts:
  path:    /liste-des-annonces-avec-les-candidatures-2017-2018-alassane
  defaults:
    _controller: OCPlatformBundle:Advert:list

##Route vers le système de purge
oc_platform_purge:
  path:    /purge/{days}
  defaults:
    _controller: OCPlatformBundle:Advert:purge
  requirements:
    days:    \d+

oc_platform_search_ajax:
  path:    /search/results
  defaults:
      _controller: OCPlatformBundle:Advert:search
  #methods: [post]

fic_2017_lille_grand_palais:
  path:    /master-ircoms-presents-au-fic-2017
  defaults: {_controller : OCPlatformBundle:Advert:fic }
