services:
  
  oc_platform.doctrine_listener.application_creation:
    class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
    arguments:
      - "@oc_platform.email.application_mailer"
    tags:
      - { name: doctrine.event_listener, event: postPersist }


  oc_platform.email.application_mailer:
    class: OC\PlatformBundle\Email\ApplicationMailer
    arguments:
      - "@mailer"

  oc_platform.antispam:
    class: OC\PlatformBundle\Antispam\OCAntispam
    arguments:
      - "@mailer"
      - 50
    # Les calls sont un moyen d'exécuter des méthodes de notre service
    # juste après sa création
    calls:
      - [ setLocale, [%locale%] ]


  oc_platform.twig.antispam_extension:
    class: OC\PlatformBundle\Twig\AntispamExtension
    arguments:
      - "@oc_platform.antispam"
    tags:
      - { name: twig.extension }


  oc_platform.form.ckeditor:
    class: OC\PlatformBundle\Form\CkeditorType
    tags:
      - { name: form.type, alias: ckeditor }



  #"--Système de purge ici--"
  oc_platform.purger.advert:
    class: OC\PlatformBundle\Purge\Purge
    arguments:
      - "@doctrine.orm.entity_manager"
      - 3 # Je veux supprimer sans candidatures de plus de 3 jours

  oc_platform.validator.antiflood:
    class: OC\PlatformBundle\Validator\AntifloodValidator
    arguments:
      - "@request_stack"
      - "@doctrine.orm.entity_manager"
    tags:
      - { name: validator.constraint_validator, alias: oc_platform_antiflood }


  oc_platform.beta.html_adder:
    class: OC\PlatformBundle\Beta\BetaHTMLAdder

  oc_platform.beta.listener:
    class: OC\PlatformBundle\Beta\BetaListener
    arguments:
      - "@oc_platform.beta.html_adder"
      - "2017-01-01"
    tags:
    #  - { name: kernel.event_listener, event: kernel.response, method: processBeta, priority: 2 }


  oc_platform.bigbrother.message_notificator:
      class: OC\PlatformBundle\Bigbrother\MessageNotificator
      arguments:
          - "@mailer"

  oc_platform.bigbrother.message_listener:
      class: OC\PlatformBundle\Bigbrother\MessageListener
      arguments:
          - "@oc_platform.bigbrother.message_notificator"
          - ["alexandre", "marine", "pierre", "OussouToure", "Ousmane ALASSANE"]
      tags:
          - { name: kernel.event_listener, event: oc_platform.post_message, method: processMessage, priority: 2 }

  oc_platform.paramconverter.json:
    class: OC\PlatformBundle\ParamConverter\JsonParamConverter
    tags:
      - { name: request.param_converter }


  


#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
