<?php

namespace OC\PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
	//Je souhaite récupérer les X dernières candidatures avec leur annonce associée
	public function getApplicationsWithAdvert($limit)
	{
		$qb = $thi->createQueryBuilder('a');

		//On effectue une jointure avec l'entité Advert
		$qb->innerJoin('a.advert', 'adv')
		   ->addSelect('adv');

		 //Puis on ne retourne que $limit resultats
		   $qb->setMaxResults($limit);

		return $qb->getQuery()->getResult();
	}

	/**
	* @param string $ip
	* @param integer $seconds
	* @return bool  True si au moins une candidature a été créé il y a moins de $seconds
	*/
	public function isFlood($ip, $seconds)
	{
		return (bool) $this->createQueryBuilder('a')
						   ->select('COUNT(a)')
						   ->where('a.date >= :date')
						   ->setParameter('date', new \Datetime($seconds.' seconds ago'))
						   ->andWhere('a.ip = :ip')
						   ->setParameter('ip', $ip)
						   ->getQuery()
						   ->getSingleScalarResult()
						   ;
	}
}
